source 'https://rubygems.org'

gem 'bundler', '>= 1.8.4'

gem 'rails', '4.2.6'
gem 'pg', '~> 0.15'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'

gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc

source 'https://rails-assets.org' do
  gem 'rails-assets-bootstrap'
  gem 'rails-assets-angular'
  gem 'rails-assets-jquery'
  gem 'rails-assets-angular-resource'
  gem 'rails-assets-angular-mocks'
  gem 'rails-assets-angular-route', '~>1.4.0'
  gem 'rails-assets-karma'
  gem 'rails-assets-karma-jasmine'
  gem 'rails-assets-karma-chrome-launcher'
end
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

group :development, :test do
  gem 'byebug'
  gem 'shoulda'
  gem 'rspec'
  gem 'rspec-rails'
  gem 'capybara'
  gem 'factory_girl_rails'
  gem 'selenium-webdriver'
  gem 'rspec-collection_matchers'
  gem 'database_cleaner'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end
